# Site
# Name of your site (displayed in the header)
name:               Tayyar Guzel, PhD
# Short bio or description (displayed in the header)
description:        Wireless, DSP, ML, AI
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:             https://avatars1.githubusercontent.com/u/16338564?s=80&v=4

title:              Tayyar Guzel, PhD
bio:                'Wireless, DSP, ML, AI'
description:        "Wireless, DSP, ML, AI"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big-2.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:                https://tayyarg.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            expanded

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: https-tayyarg-github-io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
instagram:          yolgezer_tg
twitter:            tayyarguzel
#facebook:           username
github-url:         tayyarg
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           tayyarg
#xing:              username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-151032665-1

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-polyglot

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

# Polyglot settings
languages: ["en", "tr"]
default_lang: "tr"
exclude_from_localization: ["javascript", "images", "css", "scripts", "favicon.ico"]
parallel_localization: true